/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compras;

import javax.swing.JOptionPane;

import compras.Controllers.TiendaController;

public class App {
    public static void main(String[] args) {
        Boolean condition = true;
        TiendaController tienda = new TiendaController();
        do {
            Integer eleccion = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese cual accion desea realizar: \n\t1- Agregar un Cliente"
            +"\n\t2- Agregar un Producto\n\t3- Agregar un Pedido\n\t4- Ver Productos \n\t5- Ver Pedidos\n\t6- Salir"));
            switch (eleccion) {
                case 1:
                    tienda.agregarCliente();
                    break;
                case 2:
                    tienda.agregarProducto();
                    break;
                case 3:
                    tienda.agregarPedido();
                    break;
                case 4:
                    tienda.VerProductos();
                    break;
                case 5:
                    tienda.VerPedidos();
                    break;
                case 6:
                    condition = false;
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "No eligio opcion existente");
                    break;
            }
        } while (condition);
    }
}
